### PR TITLE
Project Completed 

### PR DESCRIPTION
**Pull request by xtrmdarc**
This is the full project with all the required features. 
We request a project review.

1. Top Navigation Bar Added
2. Main Video Section
3. Recommended Video Section

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team !
### Nice job! Project looks! :+1: 

### But your project needs a few changes before it can be approved.

#### Kindly recommended Check HTML markup with this validator https://validator.w3.org/#validate_by_upload
screen

Now it shows ERROR in your code
error

### Page structure

#### Navigation bar
screen




### Please don`t forget to follow this instructions during your next projects:
screen
screen


* Also please read this article [Reasons not to use IDs in CSS](https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4) I hope it can help you a little.

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Review by pelzolga123 — APPROVED** [review]

**Comment by pelzolga123** [comment]
## Hi Team,
## Great  work, Congratulation :+1: 
You did all changes required previously. Go ahead and merge to master
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
